/**
 * Copyright 2006-2016 the original author or authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.mybatis.generator.internal;

import com.xintr.lowcode.api.basic.BaseObject;
import com.xintr.lowcode.api.util.DateUtil;
import org.apache.commons.lang3.StringUtils;
import org.mybatis.generator.api.CommentGenerator;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.*;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.MergeConstants;
import org.mybatis.generator.config.PropertyRegistry;
import org.mybatis.generator.internal.util.StringUtility;

import javax.persistence.Id;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Properties;

import static org.mybatis.generator.internal.util.StringUtility.isTrue;

/**
 * The Class DefaultCommentGenerator.
 *
 * @author Jeff Butler
 */
public class DefaultCommentGenerator implements CommentGenerator {

  /**
   * The properties.
   */
  private Properties properties;

  /**
   * The suppress date.
   */
  private boolean suppressDate;

  /**
   * The suppress all comments.
   */
  private boolean suppressAllComments;

  /**
   * The addition of table remark's comments.
   * If suppressAllComments is true, this option is ignored
   */
  private boolean addRemarkComments;

  /**
   * 是否添加主键注解
   */
  private boolean addAnnotationId;

  /**
   * javaMapper是否添加枚举
   */
  private boolean addEnumJavaMepper;

  private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

  /**
   * 作者名
   */
  private String author = "";

  /**
   * Instantiates a new default comment generator.
   */
  public DefaultCommentGenerator() {
    super();
    properties = new Properties();
    suppressDate = false;
    suppressAllComments = false;
    addRemarkComments = false;
    addAnnotationId = false;
    addEnumJavaMepper = false;
  }

  /**
   * @param compilationUnit
   */
  @Override
  public void addJavaFileComment(CompilationUnit compilationUnit) {
    // add no file level comments by default
    if (compilationUnit instanceof TopLevelClass) {
      compilationUnit.setSuperClass(new FullyQualifiedJavaType(BaseObject.class.getName()));
      compilationUnit.addSuperInterface(new FullyQualifiedJavaType(Serializable.class.getName()));
      compilationUnit.addImportedType(new FullyQualifiedJavaType(BaseObject.class.getName()));
      compilationUnit.addImportedType(new FullyQualifiedJavaType(Serializable.class.getName()));
      if (addAnnotationId) {
        compilationUnit.addImportedType(new FullyQualifiedJavaType(Id.class.getName()));
      }
    }
  }

  /**
   * mapper文件注释
   *
   * @param xmlElement
   */
  @Override
  public void addComment(XmlElement xmlElement) {
    if (suppressAllComments) {
      return;
    }

    xmlElement.addElement(new TextElement("<!--"));

    StringBuilder sb = new StringBuilder();
    sb.append("  WARNING - ");
    sb.append(MergeConstants.NEW_ELEMENT_TAG);
    xmlElement.addElement(new TextElement(sb.toString()));
    xmlElement
      .addElement(new TextElement(
        "  This element is automatically generated by MyBatis Generator, do not modify."));

    String s = getDateString();
    if (s != null) {
      sb.setLength(0);
      sb.append("  This element was generated on ");
      sb.append(s);
      sb.append('.');
      xmlElement.addElement(new TextElement(sb.toString()));
    }

    xmlElement.addElement(new TextElement("-->"));
  }

  /**
   * 添加备注
   *
   * @param rootElement
   */
  @Override
  public void addRootComment(XmlElement rootElement) {
    // add no document level comments by default
  }

  /**
   * 添加属性配置信息
   *
   * @param properties
   */
  @Override
  public void addConfigurationProperties(Properties properties) {
    this.properties.putAll(properties);

    suppressDate = isTrue(properties
      .getProperty(PropertyRegistry.COMMENT_GENERATOR_SUPPRESS_DATE));

    suppressAllComments = isTrue(properties
      .getProperty(PropertyRegistry.COMMENT_GENERATOR_SUPPRESS_ALL_COMMENTS));

    addRemarkComments = isTrue(properties
      .getProperty(PropertyRegistry.COMMENT_GENERATOR_ADD_REMARK_COMMENTS));

    addAnnotationId = isTrue(properties.getProperty("addAnnotationId"));
    addEnumJavaMepper = isTrue(properties.getProperty("addEnumJavaMepper"));

    author = properties.getProperty("author");

    String dateFormatString = properties.getProperty(PropertyRegistry.COMMENT_GENERATOR_DATE_FORMAT);
    if (StringUtility.stringHasValue(dateFormatString)) {
      dateFormat = new SimpleDateFormat(dateFormatString);
    }
  }

  /**
   * This method adds the custom javadoc tag for. You may do nothing if you do not wish to include the Javadoc tag -
   * however, if you do not include the Javadoc tag then the Java merge capability of the eclipse plugin will break.
   *
   * @param javaElement       the java element
   * @param markAsDoNotDelete the mark as do not delete
   */
  protected void addJavadocTag(JavaElement javaElement,
                               boolean markAsDoNotDelete) {

  }

  /**
   * This method returns a formated date string to include in the Javadoc tag
   * and XML comments. You may return null if you do not want the date in
   * these documentation elements.
   *
   * @return a string representing the current timestamp, or null
   */
  protected String getDateString() {
    return DateUtil.getCurrDate(DateUtil.YYYY_MM_DD_HH_MM_SS);
  }

  /**
   * (non-Javadoc)
   *
   * @see org.mybatis.generator.api.CommentGenerator#addClassComment(org.mybatis.generator.api.dom.java.InnerClass, org.mybatis.generator.api.IntrospectedTable)
   */
  @Override
  public void addClassComment(InnerClass innerClass,
                              IntrospectedTable introspectedTable) {

  }

  /**
   * (non-Javadoc)
   *
   * @see
   */
  @Override
  public void addModelClassComment(TopLevelClass topLevelClass,
                                   IntrospectedTable introspectedTable) {
    if (suppressAllComments || !addRemarkComments) {
      return;
    }

//        StringBuilder sb = new StringBuilder();

    topLevelClass.addJavaDocLine("/**");
    if (StringUtils.isNotBlank(introspectedTable.getRemarks())) {
      topLevelClass.addJavaDocLine(" * <p>" + introspectedTable.getRemarks() + "</p>");
    } else {
      topLevelClass.addJavaDocLine(" * <p>" + introspectedTable.getFullyQualifiedTable() + "</p>");
    }
    topLevelClass.addJavaDocLine(" *");
    topLevelClass.addJavaDocLine(" * @author " + author);
    topLevelClass.addJavaDocLine(" * @create: " + getDateString());

    addJavadocTag(topLevelClass, false);

    topLevelClass.addJavaDocLine(" */");
  }

  public void addModelClassComment(Interface inter,
                                   IntrospectedTable introspectedTable) {
    if (suppressAllComments || !addRemarkComments) {
      return;
    }


    inter.addJavaDocLine("/**");
    if (StringUtils.isNotBlank(introspectedTable.getRemarks())) {
      inter.addJavaDocLine(" * <p>" + introspectedTable.getRemarks() + "</p>");
    } else {
      inter.addJavaDocLine(" * <p>" + introspectedTable.getFullyQualifiedTable() + "</p>");
    }
    inter.addJavaDocLine(" *");
    inter.addJavaDocLine(" * @author " + author);
    inter.addJavaDocLine(" * @create: " + getDateString());

    addJavadocTag(inter, false);

    inter.addJavaDocLine(" */");
  }

  /**
   * 枚举注释
   *
   * @param innerEnum
   * @param introspectedTable
   */
  @Override
  public void addEnumComment(InnerEnum innerEnum,
                             IntrospectedTable introspectedTable) {
    if (suppressAllComments) {
      return;
    }

    StringBuilder sb = new StringBuilder();

    innerEnum.addJavaDocLine("/**");
    innerEnum
      .addJavaDocLine(" * This enum was generated by MyBatis Generator.");

    sb.append(" * This enum corresponds to the database table ");
    sb.append(introspectedTable.getFullyQualifiedTable());
    innerEnum.addJavaDocLine(sb.toString());

    addJavadocTag(innerEnum, false);

    innerEnum.addJavaDocLine(" */");
  }

  /**
   * java文件 属性注释
   *
   * @param field
   * @param introspectedTable
   * @param introspectedColumn
   */
  @Override
  public void addFieldComment(Field field,
                              IntrospectedTable introspectedTable,
                              IntrospectedColumn introspectedColumn) {
    if (suppressAllComments) {
      return;
    }
    if (introspectedColumn.getRemarks() != null
      && !"".equals(introspectedColumn.getRemarks())) {
      // 添加字段注释
      StringBuffer sb = new StringBuffer();
      field.addJavaDocLine("/**");
      if (introspectedColumn.getRemarks() != null) {
        sb.append(" * " + introspectedColumn.getRemarks());
      }
//            sb.append(" 所属表字段为 : ");
//            sb.append(introspectedTable.getFullyQualifiedTable());
//            sb.append('.');
//            sb.append(introspectedColumn.getActualColumnName());
      field.addJavaDocLine(sb.toString());
      // addJavadocTag(field, false);
      field.addJavaDocLine(" */");
      //添加主键注解
      addAnnotationId(field, introspectedTable);
    }
  }

  /**
   * 添加主键注解
   *
   * @param field
   * @param introspectedTable
   */
  private void addAnnotationId(Field field,
                               IntrospectedTable introspectedTable) {
    if (addAnnotationId) {
      List<IntrospectedColumn> list = introspectedTable.getPrimaryKeyColumns();
      if (list != null && !list.isEmpty()) {
        for (int i = 0; i < list.size(); i++) {
          if (StringUtils.equals(list.get(i).getActualColumnName(), field.getName())) {
            field.addJavaDocLine("@Id");
          }
        }
      }
    }
  }

  /**
   * (non-Javadoc)
   *
   * @see org.mybatis.generator.api.CommentGenerator#addFieldComment(org.mybatis.generator.api.dom.java.Field, org.mybatis.generator.api.IntrospectedTable)
   */
  @Override
  public void addFieldComment(Field field, IntrospectedTable introspectedTable) {
    if (suppressAllComments) {
      return;
    }

    StringBuilder sb = new StringBuilder();

    field.addJavaDocLine("/**");
    field
      .addJavaDocLine(" * This field was generated by MyBatis Generator.");

    sb.append(" * This field corresponds to the database table ");
    sb.append(introspectedTable.getFullyQualifiedTable());
    field.addJavaDocLine(sb.toString());

    addJavadocTag(field, false);

    field.addJavaDocLine(" */");
  }

  /**
   * (non-Javadoc)
   *
   * @see org.mybatis.generator.api.CommentGenerator#addGeneralMethodComment(org.mybatis.generator.api.dom.java.Method, org.mybatis.generator.api.IntrospectedTable)
   */
  @Override
  public void addGeneralMethodComment(Method method,
                                      IntrospectedTable introspectedTable) {
    if (suppressAllComments) {
      return;
    }

    StringBuilder sb = new StringBuilder();

    method.addJavaDocLine("/**");
    method
      .addJavaDocLine(" * This method was generated by MyBatis Generator.");

    sb.append(" * This method corresponds to the database table ");
    sb.append(introspectedTable.getFullyQualifiedTable());
    method.addJavaDocLine(sb.toString());

    addJavadocTag(method, false);

    method.addJavaDocLine(" */");
  }

  /**
   * getter方法注释
   *
   * @param method
   * @param introspectedTable
   * @param introspectedColumn
   */
  @Override
  public void addGetterComment(Method method,
                               IntrospectedTable introspectedTable,
                               IntrospectedColumn introspectedColumn) {
    if (suppressAllComments) {
      return;
    }

    StringBuilder sb = new StringBuilder();

    method.addJavaDocLine("/**");

    sb.append(" * ");
    sb.append(introspectedColumn.getRemarks());
//        sb.append(introspectedTable.getFullyQualifiedTable());
//        sb.append('.');
//        sb.append(introspectedColumn.getActualColumnName());
    method.addJavaDocLine(sb.toString());

    method.addJavaDocLine(" *");

    sb.setLength(0);
    sb.append(" * @return ");
    sb.append(introspectedTable.getFullyQualifiedTable());
    sb.append('.');
    sb.append(introspectedColumn.getActualColumnName());
    sb.append(", ");
    sb.append(introspectedColumn.getRemarks());
    method.addJavaDocLine(sb.toString());
    method.addJavaDocLine(" */");
  }

  /**
   * setter方法注释
   *
   * @param method
   * @param introspectedTable
   * @param introspectedColumn
   */
  @Override
  public void addSetterComment(Method method,
                               IntrospectedTable introspectedTable,
                               IntrospectedColumn introspectedColumn) {
    if (suppressAllComments) {
      return;
    }

    StringBuilder sb = new StringBuilder();

    method.addJavaDocLine("/**");

    sb.append(" * ");
    sb.append(introspectedColumn.getRemarks());
    method.addJavaDocLine(sb.toString());

    method.addJavaDocLine(" *");

    Parameter parm = method.getParameters().get(0);
    sb.setLength(0);
    sb.append(" * @param ");
    sb.append(parm.getName() + " ");
    sb.append(introspectedTable.getFullyQualifiedTable());
    sb.append('.');
    sb.append(introspectedColumn.getActualColumnName());
    sb.append(", ");
    sb.append(introspectedColumn.getRemarks());
    method.addJavaDocLine(sb.toString());


    method.addJavaDocLine(" */");
  }

  /**
   * (non-Javadoc)
   *
   * @see org.mybatis.generator.api.CommentGenerator#addClassComment(org.mybatis.generator.api.dom.java.InnerClass, org.mybatis.generator.api.IntrospectedTable, boolean)
   */
  @Override
  public void addClassComment(InnerClass innerClass,
                              IntrospectedTable introspectedTable, boolean markAsDoNotDelete) {
    if (suppressAllComments) {
      return;
    }

    StringBuilder sb = new StringBuilder();

    innerClass.addJavaDocLine("/**");
    innerClass
      .addJavaDocLine(" * This class was generated by MyBatis Generator.");

    sb.append(" * This class corresponds to the database table ");
    sb.append(introspectedTable.getFullyQualifiedTable());
    innerClass.addJavaDocLine(sb.toString());

    addJavadocTag(innerClass, markAsDoNotDelete);

    innerClass.addJavaDocLine(" */");
  }
}
