blank_issues_enabled: false
contact_links:
  - name: 浏览文档
    url: http://docs.marsview.com.cn/
    about: 官方文档，快速搭建后台管理系统！
  - name: 在线体验
    url: https://www.marsview.cc/login?callback=https://www.marsview.cc/
    about: 在线体验一下！
  - name: 查看官网
    url: https://www.marsview.cc/
    about: 让搭建更简单，让开发更高效！
