export { Page, PageConfig } from './Page';
export * from './Scene';
export * from './Container';
export * from './FormItems';
export * from './Layout';
export * from './EChart';
export * from './Functional';
export * from './Basic';
export * from './FeedBack';
export { BMap, BMapConfig } from './Map/BMap';
export { IFrame, IFrameConfig } from './IFrame';
import './index.less';
