#服务名
spring:
  application:
    name: marsview4j
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: yangshare2023@qq.com
    password:
    properties: { 'mail.smtp.ssl.enable', true }
    test-connection: true
    protocol: smtps
    port: 465
  #redis配置
  data:
    redis:
      host: 192.168.6.3
      port: 6379
      password:
      database: 7

#服务端口
server:
  port: 9001

#mybatis配置
mybatis:
  jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.6.3:3308/mars?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yang
  # mybatis对应的实体类
  mapper-locations: classpath:com/**/mapper/**/*.xml
  type-aliases-package: com.**.domain

#打印sql日志
logging:
  config: classpath:logback.xml
