import { lazy } from 'react';

export { default as InputConfig } from './Input/Schema';
export { default as InputPasswordConfig } from './InputPassword/Schema';
export { default as InputNumberConfig } from './InputNumber/Schema';
export { default as InputOTPConfig } from './InputOTP/Schema';
export { default as TextAreaConfig } from './TextArea/Schema';
export { default as DatePickerConfig } from './DatePicker/Schema';
export { default as DatePickerRangeConfig } from './DatePickerRange/Schema';
export { default as RadioConfig } from './Radio/Schema';
export { default as SelectConfig } from './Select/Schema';
export { default as SwitchConfig } from './Switch/Schema';
export { default as UploadConfig } from './Upload/Schema';
export { default as StaticItemConfig } from './StaticItem/Schema';
export { default as FormItemConfig } from './FormItem/Schema';
export { default as CheckBoxConfig } from './CheckBox/Schema';
export { default as TimePickerConfig } from './TimePicker/Schema';
export { default as TimePickerRangeConfig } from './TimePickerRange/Schema';
export { default as SegmentedConfig } from './Segmented/Schema';
export { default as CascaderConfig } from './Cascader/Schema';
export { default as SliderConfig } from './Slider/Schema';
export { default as TreeSelectConfig } from './TreeSelect/Schema';
export { default as FormListConfig } from './FormList/Schema';
export { default as EditTableConfig } from './EditTable/Schema';
export { default as RichTextConfig } from './RichText/Schema';

export const Input = lazy(() => import('./Input/Input'));
export const InputPassword = lazy(() => import('./InputPassword/InputPassword'));
export const InputNumber = lazy(() => import('./InputNumber/InputNumber'));
export const InputOTP = lazy(() => import('./InputOTP/InputOTP'));
export const TextArea = lazy(() => import('./TextArea/TextArea'));
export const DatePicker = lazy(() => import('./DatePicker/DatePicker'));
export const DatePickerRange = lazy(() => import('./DatePickerRange/DatePickerRange'));
export const Radio = lazy(() => import('./Radio/Radio'));
export const Select = lazy(() => import('./Select/Select'));
export const Switch = lazy(() => import('./Switch/Switch'));
export const Upload = lazy(() => import('./Upload/Upload'));
export const StaticItem = lazy(() => import('./StaticItem/StaticItem'));
export const FormItem = lazy(() => import('./FormItem/FormItem'));
export const CheckBox = lazy(() => import('./CheckBox/CheckBox'));
export const TimePicker = lazy(() => import('./TimePicker/TimePicker'));
export const TimePickerRange = lazy(() => import('./TimePickerRange/TimePickerRange'));
export const Segmented = lazy(() => import('./Segmented/Segmented'));
export const Cascader = lazy(() => import('./Cascader/Cascader'));
export const Slider = lazy(() => import('./Slider/Slider'));
export const TreeSelect = lazy(() => import('./TreeSelect/TreeSelect'));
export const FormList = lazy(() => import('./FormList/FormList'));
export const EditTable = lazy(() => import('./EditTable/EditTable'));
export const RichText = lazy(() => import('./RichText/RichText'));
